### ISSUE TITLE
Question about def inverse_warping

### ISSUE THREAD

**Issue by Pixie8888** [KaiqiangXiong/CL-MVSNet#8]
Hi,

Thank you for sharing code! I have a question regarding ```def inverse_warping```. Are ```R_left``` and ```t_left``` the world to camera transformation?

<img width="585" alt="image" src="https://github.com/user-attachments/assets/f8be8d1f-1315-4880-9031-2a79cee07420">

**Comment by KaiqiangXiong** [comment]
Yes, R_left and t_left are the rotation matrix and the translation vector of the camera extrinsic, which is also called world2camera transformation.

**Comment by Pixie8888** [comment]
Hi,
Thank you for your reply! I still have some doubt. Why are the ```ref_img``` and ```view_img``` interpolated? After interpolation, shouldn't the intrinsic be changed (divided by the resized ratio) when doing inverse warping?
![image](https://github.com/user-attachments/assets/a750390b-bf70-4437-bcf9-866c27465c2d)

![image](https://github.com/user-attachments/assets/6b5bd9d6-bcf0-41db-ba91-9196c34d6d40)

**Comment by KaiqiangXiong** [comment]
Images are interpolated because the model contains 3 stages, where the output depth map resolution(H x W) of the 3 stages is (0.25 x 0.25), (0.5 x 0.5), and (1 x 1), respectively. So the corresponding images have to be interpolated to the same size as the inferred depth maps. We precompute 3 sets of camera parameters in the datasets/dtu_cl.py code, where different stages have different intrinsics. As for the code you cropped, we pick the current right camera parameters according to **stage_key**.
![7961722493502_ pic](https://github.com/user-attachments/assets/bfe7793e-07b5-40be-8681-758a1baf42b9)

**Comment by Pixie8888** [comment]
Thanks!
